# Generated by Django 5.2.4 on 2025-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='teacher_image')),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='teacher_cv/')),
            ],
        ),
    ]
