# Generated by Django 5.2.4 on 2025-07-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(unique=True)),
                ('class_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='teacher_cv'),
        ),
    ]
