# Generated by Django 5.2.4 on 2025-08-10 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notice title', max_length=200)),
                ('content', models.TextField(help_text='Notice content/description')),
                ('category', models.CharField(choices=[('URGENT', 'Urgent'), ('ACADEMIC', 'Academic'), ('EVENT', 'Event'), ('ADMISSIONS', 'Admissions'), ('RESULTS', 'Results'), ('HOLIDAY', 'Holiday'), ('FEE', 'Fee'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('posted_by', models.CharField(help_text="Posted by (e.g., Principal's Office, Examination Cell)", max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_urgent', models.BooleanField(default=False, help_text='Mark as urgent notice')),
                ('is_active', models.BooleanField(default=True, help_text='Show on notice board')),
                ('button_text', models.CharField(blank=True, help_text='Button text (e.g., Read More, Download)', max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, help_text='Button link URL', null=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-is_urgent', '-date_posted'],
            },
        ),
    ]
