# Generated by Django 5.2.4 on 2025-08-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='button_link',
        ),
        migrations.AddField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file for this notice', null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='button_text',
            field=models.CharField(blank=True, help_text='Button text (e.g., Download, View Details)', max_length=50, null=True),
        ),
    ]
