# Generated by Django 5.2.4 on 2025-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks_portal', '0002_remove_notice_button_link_notice_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_urgent', '-date_posted']},
        ),
        migrations.AlterField(
            model_name='notice',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notices/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
