# Generated by Django 5.2.4 on 2025-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('std', models.IntegerField(blank=True, null=True)),
                ('father', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='student_image')),
            ],
        ),
    ]
