# Generated by Django 5.2.4 on 2025-07-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_front_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bengali_first_theory', models.IntegerField(blank=True, null=True)),
                ('bengali_first_practical', models.IntegerField(blank=True, null=True)),
                ('bengali_second_theory', models.IntegerField(blank=True, null=True)),
                ('bengali_second_practical', models.IntegerField(blank=True, null=True)),
                ('bengali_third_theory', models.IntegerField(blank=True, null=True)),
                ('bengali_third_practical', models.IntegerField(blank=True, null=True)),
                ('english_first_theory', models.IntegerField(blank=True, null=True)),
                ('english_first_practical', models.IntegerField(blank=True, null=True)),
                ('english_second_theory', models.IntegerField(blank=True, null=True)),
                ('english_second_practical', models.IntegerField(blank=True, null=True)),
                ('english_third_theory', models.IntegerField(blank=True, null=True)),
                ('english_third_practical', models.IntegerField(blank=True, null=True)),
                ('mathematics_first_theory', models.IntegerField(blank=True, null=True)),
                ('mathematics_first_practical', models.IntegerField(blank=True, null=True)),
                ('mathematics_second_theory', models.IntegerField(blank=True, null=True)),
                ('mathematics_second_practical', models.IntegerField(blank=True, null=True)),
                ('mathematics_third_theory', models.IntegerField(blank=True, null=True)),
                ('mathematics_third_practical', models.IntegerField(blank=True, null=True)),
                ('physical_science_first_theory', models.IntegerField(blank=True, null=True)),
                ('physical_science_first_practical', models.IntegerField(blank=True, null=True)),
                ('physical_science_second_theory', models.IntegerField(blank=True, null=True)),
                ('physical_science_second_practical', models.IntegerField(blank=True, null=True)),
                ('physical_science_third_theory', models.IntegerField(blank=True, null=True)),
                ('physical_science_third_practical', models.IntegerField(blank=True, null=True)),
                ('life_science_first_theory', models.IntegerField(blank=True, null=True)),
                ('life_science_first_practical', models.IntegerField(blank=True, null=True)),
                ('life_science_second_theory', models.IntegerField(blank=True, null=True)),
                ('life_science_second_practical', models.IntegerField(blank=True, null=True)),
                ('life_science_third_theory', models.IntegerField(blank=True, null=True)),
                ('life_science_third_practical', models.IntegerField(blank=True, null=True)),
                ('history_first_theory', models.IntegerField(blank=True, null=True)),
                ('history_first_practical', models.IntegerField(blank=True, null=True)),
                ('history_second_theory', models.IntegerField(blank=True, null=True)),
                ('history_second_practical', models.IntegerField(blank=True, null=True)),
                ('history_third_theory', models.IntegerField(blank=True, null=True)),
                ('history_third_practical', models.IntegerField(blank=True, null=True)),
                ('geography_first_theory', models.IntegerField(blank=True, null=True)),
                ('geography_first_practical', models.IntegerField(blank=True, null=True)),
                ('geography_second_theory', models.IntegerField(blank=True, null=True)),
                ('geography_second_practical', models.IntegerField(blank=True, null=True)),
                ('geography_third_theory', models.IntegerField(blank=True, null=True)),
                ('geography_third_practical', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_front_login.student')),
            ],
        ),
    ]
